import {
  PhBell,
  PhChartBar,
  PhChartPieSlice,
  PhCheck,
  PhCode,
  PhCornersIn,
  PhCornersOut,
  PhCopy,
  PhCrosshair,
  PhCursorClick,
  PhDatabase,
  PhDownload,
  PhDotsSixVertical,
  PhDotsThreeVertical,
  PhEnvelope,
  PhEye,
  PhGear,
  PhGithubLogo,
  PhHouse,
  PhImage,
  PhKey,
  PhLayout,
  PhLink,
  PhList,
  PhListBullets,
  PhLock,
  PhLockOpen,
  PhMagnifyingGlass,
  PhMapPinArea,
  PhMoon,
  PhPalette,
  PhPushPin,
  PhPushPinSlash,
  PhQuestion,
  PhRepeat,
  PhArrowsDownUp,
  PhShield,
  PhShieldCheck,
  PhShieldWarning,
  PhSignOut,
  PhSquaresFour,
  PhSun,
  PhTabs,
  PhTextT,
  PhTextIndent,
  PhTextOutdent,
  PhUser,
  PhUserCheck,
  PhUserCircle,
  PhUserCircleGear,
  PhUserCirclePlus,
  PhUserList,
  PhUserGear,
  PhUsers,
  PhWarningCircle,
  PhX,
} from '@phosphor-icons/vue'
import {
  IconBell,
  IconBrandGithub,
  IconChartBar,
  IconChartPie,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCode,
  IconCopy,
  IconDatabase,
  IconDownload,
  IconDotsVertical,
  IconEye,
  IconFocus2,
  IconGripVertical,
  IconHome,
  IconIcons,
  IconIndentDecrease,
  IconIndentIncrease,
  IconKey,
  IconLayout,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconListDetails,
  IconLock,
  IconMail,
  IconMapPinQuestion,
  IconMenu,
  IconMenu2,
  IconMoon,
  IconPalette,
  IconPhoto,
  IconPinned,
  IconPinnedOff,
  IconPointer,
  IconQuestionMark,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconArrowsSort,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconShieldPlus,
  IconShieldX,
  IconSignRight,
  IconSun,
  IconTable,
  IconTextSize,
  IconUser,
  IconUserCheck,
  IconUserCircle,
  IconUserCog,
  IconUserPlus,
  IconUsers,
  IconX,
} from '@tabler/icons-vue'
import type { Component } from 'vue'

export const phosphorIconComponents = {
  bell: PhBell,
  'chart-bar': PhChartBar,
  'chart-pie-slice': PhChartPieSlice,
  check: PhCheck,
  code: PhCode,
  minimize: PhCornersIn,
  maximize: PhCornersOut,
  copy: PhCopy,
  'cursor-click': PhCursorClick,
  database: PhDatabase,
  download: PhDownload,
  'dots-three-vertical': PhDotsThreeVertical,
  'dots-six-vertical': PhDotsSixVertical,
  'drag-handle': PhDotsSixVertical,
  envelope: PhEnvelope,
  eye: PhEye,
  'focus-2': PhCrosshair,
  gear: PhGear,
  github: PhGithubLogo,
  'github-logo': PhGithubLogo,
  house: PhHouse,
  image: PhImage,
  key: PhKey,
  layout: PhLayout,
  link: PhLink,
  list: PhList,
  'list-bullets': PhListBullets,
  lock: PhLock,
  'lock-open': PhLockOpen,
  'magnifying-glass': PhMagnifyingGlass,
  'map-pin-area': PhMapPinArea,
  moon: PhMoon,
  palette: PhPalette,
  pin: PhPushPin,
  'pin-off': PhPushPinSlash,
  'push-pin': PhPushPin,
  question: PhQuestion,
  refresh: PhRepeat,
  sortable: PhArrowsDownUp,
  shield: PhShield,
  'shield-check': PhShieldCheck,
  'shield-warning': PhShieldWarning,
  'sign-out': PhSignOut,
  'squares-four': PhSquaresFour,
  sun: PhSun,
  tabs: PhTabs,
  text: PhTextT,
  'text-indent': PhTextIndent,
  'text-outdent': PhTextOutdent,
  user: PhUser,
  view: PhEye,
  'user-check': PhUserCheck,
  'user-circle': PhUserCircle,
  'user-circle-gear': PhUserCircleGear,
  'user-circle-plus': PhUserCirclePlus,
  'user-list': PhUserList,
  'user-gear': PhUserGear,
  users: PhUsers,
  'warning-circle': PhWarningCircle,
  x: PhX,
} satisfies Record<string, Component>

export const tablerIconComponents = {
  bell: IconBell,
  'brand-github': IconBrandGithub,
  'chart-bar': IconChartBar,
  'chart-pie': IconChartPie,
  check: IconCheck,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  code: IconCode,
  copy: IconCopy,
  database: IconDatabase,
  download: IconDownload,
  'dots-vertical': IconDotsVertical,
  eye: IconEye,
  'focus-2': IconFocus2,
  'grip-vertical': IconGripVertical,
  'drag-handle': IconGripVertical,
  home: IconHome,
  icons: IconIcons,
  'indent-decrease': IconIndentDecrease,
  'indent-increase': IconIndentIncrease,
  key: IconKey,
  layout: IconLayout,
  'layout-dashboard': IconLayoutDashboard,
  link: IconLink,
  list: IconList,
  'list-details': IconListDetails,
  lock: IconLock,
  mail: IconMail,
  'map-pin-question': IconMapPinQuestion,
  menu: IconMenu,
  'menu-2': IconMenu2,
  moon: IconMoon,
  palette: IconPalette,
  photo: IconPhoto,
  pinned: IconPinned,
  'pinned-off': IconPinnedOff,
  pointer: IconPointer,
  'question-mark': IconQuestionMark,
  refresh: IconRefresh,
  search: IconSearch,
  settings: IconSettings,
  sortable: IconArrowsSort,
  shield: IconShield,
  'shield-check': IconShieldCheck,
  'shield-lock': IconShieldLock,
  'shield-plus': IconShieldPlus,
  'shield-x': IconShieldX,
  'sign-right': IconSignRight,
  sun: IconSun,
  table: IconTable,
  'text-size': IconTextSize,
  user: IconUser,
  'user-check': IconUserCheck,
  'user-circle': IconUserCircle,
  'user-cog': IconUserCog,
  'user-plus': IconUserPlus,
  users: IconUsers,
  x: IconX,
} satisfies Record<string, Component>

export type PhosphorIconName = keyof typeof phosphorIconComponents
export type TablerIconName = keyof typeof tablerIconComponents
