import {
  PhBell,
  PhChartBar,
  PhChartPieSlice,
  PhCheck,
  PhCode,
  PhCornersIn,
  PhCornersOut,
  PhCopy,
  PhCrosshair,
  PhCursorClick,
  PhDatabase,
  PhDownload,
  PhDotsSixVertical,
  PhDotsThreeVertical,
  PhEnvelope,
  PhEye,
  PhGear,
  PhGithubLogo,
  PhHouse,
  PhImage,
  PhKey,
  PhLayout,
  PhLink,
  PhList,
  PhListBullets,
  PhLock,
  PhLockOpen,
  PhMagnifyingGlass,
  PhMapPinArea,
  PhMoon,
  PhPalette,
  PhPushPin,
  PhPushPinSlash,
  PhQuestion,
  PhRepeat,
  PhArrowsDownUp,
  PhShield,
  PhShieldCheck,
  PhShieldWarning,
  PhSignOut,
  PhSquaresFour,
  PhSun,
  PhTabs,
  PhTextT,
  PhTextIndent,
  PhTextOutdent,
  PhUser,
  PhUserCheck,
  PhUserCircle,
  PhUserCircleGear,
  PhUserCirclePlus,
  PhUserList,
  PhUserGear,
  PhUsers,
  PhWarningCircle,
  PhX,
} from '@phosphor-icons/vue'
import type { Component } from 'vue'

export const phosphorIconComponents = {
  bell: PhBell,
  'chart-bar': PhChartBar,
  'chart-pie-slice': PhChartPieSlice,
  check: PhCheck,
  code: PhCode,
  minimize: PhCornersIn,
  maximize: PhCornersOut,
  copy: PhCopy,
  'cursor-click': PhCursorClick,
  database: PhDatabase,
  download: PhDownload,
  'dots-three-vertical': PhDotsThreeVertical,
  'dots-six-vertical': PhDotsSixVertical,
  'drag-handle': PhDotsSixVertical,
  envelope: PhEnvelope,
  eye: PhEye,
  'focus-2': PhCrosshair,
  gear: PhGear,
  github: PhGithubLogo,
  'github-logo': PhGithubLogo,
  house: PhHouse,
  image: PhImage,
  key: PhKey,
  layout: PhLayout,
  link: PhLink,
  list: PhList,
  'list-bullets': PhListBullets,
  lock: PhLock,
  'lock-open': PhLockOpen,
  'magnifying-glass': PhMagnifyingGlass,
  'map-pin-area': PhMapPinArea,
  moon: PhMoon,
  palette: PhPalette,
  pin: PhPushPin,
  'pin-off': PhPushPinSlash,
  'push-pin': PhPushPin,
  question: PhQuestion,
  refresh: PhRepeat,
  sortable: PhArrowsDownUp,
  shield: PhShield,
  'shield-check': PhShieldCheck,
  'shield-warning': PhShieldWarning,
  'sign-out': PhSignOut,
  'squares-four': PhSquaresFour,
  sun: PhSun,
  tabs: PhTabs,
  text: PhTextT,
  'text-indent': PhTextIndent,
  'text-outdent': PhTextOutdent,
  user: PhUser,
  view: PhEye,
  'user-check': PhUserCheck,
  'user-circle': PhUserCircle,
  'user-circle-gear': PhUserCircleGear,
  'user-circle-plus': PhUserCirclePlus,
  'user-list': PhUserList,
  'user-gear': PhUserGear,
  users: PhUsers,
  'warning-circle': PhWarningCircle,
  x: PhX,
} satisfies Record<string, Component>

export type PhosphorIconName = keyof typeof phosphorIconComponents
