import {
  IconBell,
  IconBrandGithub,
  IconChartBar,
  IconChartPie,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCode,
  IconCopy,
  IconDatabase,
  IconDownload,
  IconDotsVertical,
  IconEye,
  IconFocus2,
  IconGripVertical,
  IconHome,
  IconIcons,
  IconIndentDecrease,
  IconIndentIncrease,
  IconKey,
  IconLayout,
  IconLayoutDashboard,
  IconLink,
  IconList,
  IconListDetails,
  IconLock,
  IconMail,
  IconMapPinQuestion,
  IconMenu,
  IconMenu2,
  IconMoon,
  IconPalette,
  IconPhoto,
  IconPinned,
  IconPinnedOff,
  IconPointer,
  IconQuestionMark,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconArrowsSort,
  IconShield,
  IconShieldCheck,
  IconShieldLock,
  IconShieldPlus,
  IconShieldX,
  IconSignRight,
  IconSun,
  IconTable,
  IconTextSize,
  IconUser,
  IconUserCheck,
  IconUserCircle,
  IconUserCog,
  IconUserPlus,
  IconUsers,
  IconX,
} from '@tabler/icons-vue'
import type { Component } from 'vue'

export const tablerIconComponents = {
  bell: IconBell,
  'brand-github': IconBrandGithub,
  'chart-bar': IconChartBar,
  'chart-pie': IconChartPie,
  check: IconCheck,
  'chevron-left': IconChevronLeft,
  'chevron-right': IconChevronRight,
  code: IconCode,
  copy: IconCopy,
  database: IconDatabase,
  download: IconDownload,
  'dots-vertical': IconDotsVertical,
  eye: IconEye,
  'focus-2': IconFocus2,
  'grip-vertical': IconGripVertical,
  'drag-handle': IconGripVertical,
  home: IconHome,
  icons: IconIcons,
  'indent-decrease': IconIndentDecrease,
  'indent-increase': IconIndentIncrease,
  key: IconKey,
  layout: IconLayout,
  'layout-dashboard': IconLayoutDashboard,
  link: IconLink,
  list: IconList,
  'list-details': IconListDetails,
  lock: IconLock,
  mail: IconMail,
  'map-pin-question': IconMapPinQuestion,
  menu: IconMenu,
  'menu-2': IconMenu2,
  moon: IconMoon,
  palette: IconPalette,
  photo: IconPhoto,
  pinned: IconPinned,
  'pinned-off': IconPinnedOff,
  pointer: IconPointer,
  'question-mark': IconQuestionMark,
  refresh: IconRefresh,
  search: IconSearch,
  settings: IconSettings,
  sortable: IconArrowsSort,
  shield: IconShield,
  'shield-check': IconShieldCheck,
  'shield-lock': IconShieldLock,
  'shield-plus': IconShieldPlus,
  'shield-x': IconShieldX,
  'sign-right': IconSignRight,
  sun: IconSun,
  table: IconTable,
  'text-size': IconTextSize,
  user: IconUser,
  'user-check': IconUserCheck,
  'user-circle': IconUserCircle,
  'user-cog': IconUserCog,
  'user-plus': IconUserPlus,
  users: IconUsers,
  x: IconX,
} satisfies Record<string, Component>

export type TablerIconName = keyof typeof tablerIconComponents
